### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by ChristopherHogan** [HomerReid/libGDSII#2]
Would it be possible to create a `0.2` release so I can create a conda package on `conda-forge`?  Also, can you create the release tarball using `make dist` so the user won't have to run `autogen.sh`?  Thanks!

**Comment by HomerReid** [comment]
Hey, let me know if this is what you need---I needed to add one missing file (`COPYRIGHT`) to enable `make dist` to work on my machine, but it did work---should I send you that `.tar.gz` file, or perhaps upload it here? Other than that I haven't changed anything, so I guess the 0.2 release tag is something of a formality associated with the Conda packaging system? Or, if I'm missing something let me know and I'll be happy to take care of it.

**Comment by ChristopherHogan** [comment]
> should I send you that .tar.gz file, or perhaps upload it here?

It should be uploaded as a release asset on the releases page, just like the [Meep release page](https://github.com/NanoComp/meep/releases).

> Other than that I haven't changed anything, so I guess the 0.2 release tag is something of a formality associated with the Conda packaging system? 

It looks like there were several [changes](https://github.com/HomerReid/libGDSII/compare/0.1...master) since the `0.1` release. But yes, the only reason it's necessary is because conda-forge won't let me create packages from the HEAD of a git repo. They only accept official release tarballs.

Thanks for taking care of it.

**Comment by ChristopherHogan** [comment]
Any update on this?

**Comment by HomerReid** [comment]
Whoops, is there something else I need to do? I thought this was already a done deal, and didn't realize you were still waiting for something from me. I'm sorry to keep you waiting---let me know what I missed and I'll take care of it ASAP.

**Comment by ChristopherHogan** [comment]
See my previous comment. The tarball created by `make dist` should be uploaded to the release assets page.

**Comment by HomerReid** [comment]
My mistake. I misinterpreted your comment to mean that the tarball upload should happen automatically, and I didn't realize you had been waiting all this time for me to do it---my apologies! 

I tried again with release v0.21, which includes a minor thing I added yesterday. I hope this will do the trick---definitely let me know if you need anything else.

**Comment by ChristopherHogan** [comment]
Awesome. Thank you.
